### ISSUE TITLE
Avatar in AppBar rendering incorrectly in Safari

### ISSUE THREAD

**Issue by trentpeterson** [skeletonlabs/skeleton#2055] opened 2023-09-18 18:41 UTC
### Current Behavior

In Safari on MacOS (Version 16.6 (18615.3.12.11.2), Ventura 13.5.2) with Skeleton 2.1.0, Skeleton Tailwind 0.2.0, and Tailwind 3.3.3, I'm observing that the Avatar component causes the entire contents of the AppBar to render in the middle of the viewport when placed in the trail slot.

This issue sounds very similar to the issue described in #1699.

### Expected Behavior

The contents of the AppBar should be properly vertically centered within it as it is in Chrome and in previous versions of Skeleton.

### Steps To Reproduce

Locally, this reproduces with the following snippet:
```
<AppBar>
  <svelte:fragment slot="lead">
    <strong class="text-xl uppercase">test</strong>
  </svelte:fragment>
  <svelte:fragment slot="trail">
    <Avatar initials="sk" />
  </svelte:fragment>
</AppBar>
```

I was also able to reproduce in a hokey way by manually inserting the rendered HTML from an Avatar component into an AppBar's rendered HTML within the Skeleton docs.

### Link to Reproduction / Stackblitz

Is there a StackBlitz with newer 2.x Skeleton and 4.x Svelte (One on the homepage appears to be 1.x/3.x)? Thought I'd ask before I put one together.

### More Information

I managed to workaround the issue by overriding the `aspect-square` class applied to the div rendered by an Avatar with `.avatar.aspect-square { aspect-ratio: auto }`.

**Comment by endigo9740** [comment] 2023-09-18 18:54
Since it looks like you're testing with a modern version of Tailwind and Safari, can you also share the contents of your `tailwind.config.[ts|js]` please.

> Is there a StackBlitz with newer 2.x Skeleton
Not yet, but soon per:
https://github.com/skeletonlabs/skeleton/issues/1995

**Comment by trentpeterson** [comment] 2023-09-18 19:12
Thanks for the quick reply.

tailwind.config.ts:

```
import { join } from 'path'
import type { Config } from 'tailwindcss'
import { skeleton } from '@skeletonlabs/tw-plugin'
import { planshipTheme } from './src/lib/styles/theme.ts'

const config = {
  darkMode: 'class',
  content: [
    './src/**/*.{html,js,svelte,ts}',
    join(require.resolve(
      '@skeletonlabs/skeleton'),
      '../**/*.{html,js,svelte,ts}'
    )
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
    skeleton({
      base: true,
      themes: {
        custom: [ planshipTheme ]
      }
    })
  ]
} satisfies Config

export default config

```

> Not yet, but soon per:
https://github.com/skeletonlabs/skeleton/issues/1995

👍

**Comment by endigo9740** [comment] 2023-09-18 19:36
@trentpeterson it just occurred to me we have some default styles that affect the Trail slot. The expectation is most folks will want a series of horizontal items in that slot. For example:

```
button button button
```

This COULD be the reason the avatar is affected in this manner. Can you try wrapping the avatar in a simple `div` without any other classes applied. Like so:

```html
<AppBar>
  <svelte:fragment slot="lead">
    <strong class="text-xl uppercase">test</strong>
  </svelte:fragment>
  <svelte:fragment slot="trail">
    <Avatar initials="sk" />
  </svelte:fragment>
</AppBar>
```

If this resolves your issue I may look to adjust the behavior of this component and the slot styles. What we have now may be too opinionated

**Comment by trentpeterson** [comment] 2023-09-19 16:10
Interestingly, if I remove `h-full` from the svg without removing `aspect-square` from the figure, the issue also goes away.

**Comment by endigo9740** [comment] 2023-09-19 16:41
@trentpeterson as a temporary work around here's a solution that does appear to work if you're adverse to the App Shell:

```html
<script lang="ts">
  import "../app.postcss";
  import { AppBar, Avatar } from "@skeletonlabs/skeleton";
</script>

<main class="grid grid-rows-[auto_1fr]">
  <AppBar>
    <svelte:fragment slot="lead">
      <Avatar initials="sk" />
    </svelte:fragment>
    <svelte:fragment slot="trail">
      <strong class="text-xl uppercase">test</strong>
    </svelte:fragment>
  </AppBar>
  <div>
    <slot />
  </div>
</main>
```

So far best I can tell the App Bar needs some kind of defined wrapping parent element that squishes it into size vertically, otherwise it (visually) tries to fill the height of the container. Using grid styling accomplishes this a lot like the App Shell.

**Comment by trentpeterson** [comment] 2023-09-19 16:52
> > Interestingly, if I remove h-full from the svg without removing aspect-square from the figure, the issue also goes away.
> 
> Not sure I follow - this is the first mention about an SVG. Not sure how that comes into play here.

I'm manipulating the resulting HTML in the inspector, which [contains an svg](https://github.com/skeletonlabs/skeleton/blob/dev/packages/skeleton/src/lib/components/Avatar/Avatar.svelte#L66) when initials are used. To be fair, it also happens if I remove the `h-full` class from the `img` when src is provided. Basically, there appears to be some conflict within Safari between aspect-ratio set to 1/1 on the parent while the child has a height specified as anything besides `auto`. No idea if this is helpful...

```
<figure class="avatar flex aspect-square text-surface-50 font-semibold justify-center items-center overflow-hidden isolate bg-surface-400-500-token w-16  rounded-full   " data-testid="avatar">
  <svg class="avatar-initials w-full h-full" viewBox="0 0 512 512">
    <text x="50%" y="50%" dominant-baseline="central" text-anchor="middle" font-weight="bold" font-size="150" class="avatar-text fill-token">
      SK
    </text>
  </svg>
</figure>
```

> While Trent's aspect ratio class change may work, I don't think that's an ideal solution here. Users shouldn't have to modify a default Tailwind class for these components to work as expected.

Absolutely agree. It's working for me, specifically right at this moment, but it's definitely a hasty hack to move forward. Granted, users wouldn't have to modify/override Tailwind if Skeleton didn't specify the `aspect-square` class on the figure, but I imagine there's a good reason for having it there in certain circumstances.

> @trentpeterson I'm limited on time today so I'll have to circle back on this. But it's definitely an odd issue, and definitely one we'll try to resolve if we can.

I appreciate the attention you've already provided. I have a workaround for now so I'm good.

> @trentpeterson as a temporary work around here's a solution that does appear to work if you're adverse to the App Shell

Thanks for this! I'll give it a shot. I'll also follow up on Discord as I have some general questions about App Shell usage, etc.

**Comment by szethh** [comment] 2023-09-25 10:56
I have the same issue. The Avatar causes all elements in the AppBar to appear in the middle of the page, in macOS and iOS (safari).

I am using an AppShell:

```svelte
<AppShell slotPageContent="m-8">
	<svelte:fragment slot="header"
		><AppBar>
			<svelte:fragment slot="lead">
				<a href="/" class="flex items-center gap-4">
					<img src="/favicon.png" height="1rem" alt="logo" class="w-16" />

					<span class="text-xl font-extralight font-heading-token">App title</span>
				</a>
			</svelte:fragment>

			<svelte:fragment slot="trail">
				<LightSwitch />


				<div> // tried with & without a parent div - no change
					<Avatar
						border="border-4 border-surface-300-600-token hover:!border-primary-500"
						cursor="cursor-pointer"
						{initials}
					/>
				</div>

			</svelte:fragment>
		</AppBar>
	</svelte:fragment>

	<slot />
</AppShell>
```

The issue is fixed by removing `h-full` from the svg:

```diff
<figure class="avatar flex aspect-square text-surface-50 font-semibold justify-center items-center overflow-hidden isolate bg-surface-400-500-token w-16 border-4 border-surface-300-600-token hover:!border-primary-500 rounded-full  cursor-pointer " data-testid="avatar">
-     <svg class="avatar-initials w-full h-full" viewBox="0 0 512 512">
+     <svg class="avatar-initials w-full" viewBox="0 0 512 512">
        <text x="50%" y="50%" dominant-baseline="central" text-anchor="middle" font-weight="bold" font-size="150" class="avatar-text fill-token">CP</text>
    </svg>
</figure>
```

**Closed** 2023-12-20 17:38 UTC
Labels: bug
