### ISSUE TITLE
Opacity does not work when using color tokens

### ISSUE THREAD

**Issue by multiwebinc** [skeletonlabs/skeleton#1494] opened 2023-05-12 21:26 UTC
### Current Behavior

The following work:

```
<div class="bg-surface-50-900-token"></div>
<div class="bg-surface-500/25"></div>

<div class="text-surface-50-900-token"></div>
<div class="text-surface-500/25"></div>

<div class="ring-surface-50-900-token"></div>
<div class="ring-surface-500/25"></div>
```

The following work, but produce a warning when using eslint [tailwindcss/classnames-order](https://github.com/francoismassart/eslint-plugin-tailwindcss/tree/master/docs/rules/classnames-order.md):

```
<div class="bg-surface-50-900-token bg-opacity-25"></div>
<div class="text-surface-50-900-token text-opacity-25"></div>
<div class="ring-surface-50-900-token ring-opacity-25"></div>
```

> Classname 'ring-opacity-25' should be replaced by an opacity suffix (eg. '/25')

But the following don't work:

```
<div class="bg-surface-50-900-token/25"></div>
<div class="text-surface-50-900-token/25"></div>
<div class="ring-surface-50-900-token/25"></div>

```

**Comment by Sarenor** [comment] 2023-05-13 13:53
Our resident CSS Wizard and general package author @endigo9740 is in his well deserved weekend break and I'm far less proficient with CSS and Tailwind in general, but I think that's expected behaviour and pretty much impossible for us to reproduce unless we replicate the Tailwind compiler.

Our tokens are static css classes that are just generated for you. No Tailwind compiler magic that allows for arbitrary opacity, I'm afraid.

But that's only my dabbling knowledge, I very well be wrong, just didn't want to leave you hanging until Monday!

**Comment by endigo9740** [comment] 2023-05-14 06:18
Unfortunately this is not supported. Primitive color values like `bg-primary-500/50` work because they are just an RGB value passed to Tailwind. Tailwind provides several means to manipulate these classes.

Our design token classes are utility tokens, but work as a combination of other classes, for example:

```css
.bg-surface-50-900-token { @apply bg-surface-50 dark:bg-surface-900; }
```

So while they may appear the same from the outside, they're very different within. Unfortunately unless Tailwind implements a mean for us to pass the opacity down, this will not be possible.

Given this I'm going to go ahead and close this out. Unfortunately this is not a bug and not a feature request that's technically possible at the moment.

**Closed by endigo9740** 2023-05-14 06:18 UTC
Labels: bug
