### ISSUE TITLE
TreeViewItem does not work with Svelte 5

### ISSUE THREAD

**Issue by notramo** [skeletonlabs/skeleton#2502] opened 2024-02-22 17:23 UTC
### Current Behavior

It seems it's using a `children` attribute which is reserved in Svelte 5 for the default snippet.

### Expected Behavior

Rename `children` to `childNodes` or similar.

### Steps To Reproduce

Use `TreeViewItem` in a Svelte 5 project.

**Comment by endigo9740** [comment] 2024-02-22 18:06
> Use TreeViewItem in a Svelte 5 project.

You shouldn't be doing this:

- https://github.com/skeletonlabs/skeleton/discussions/2400
- https://svelte-5-preview.vercel.app/status

One of the key focuses of Skeleton v3 (our next major version) is support for Svelte 5. This will not be available on the `v2.x` version of Skeleton.

I'm going to assign this to @Mahmoud-zino (author of the Tree View feature) to determine if this is relevant to fix for Skeleton v3, given, we do expect other changes to occur as part of the process of porting from Svelte 4 -> 5. I defer to him on this.

**Comment by Mahmoud-zino** [comment] 2024-02-22 18:41
This is not a bug, there was no way we could have predicted that :smile: 
However this will change for sure in Skeleton v3

**Closed by Mahmoud-zino** 2024-02-22 18:41 UTC
Labels: bug
