### ISSUE TITLE
autocomplete popup is not align with input

### ISSUE THREAD

**Issue by vuthanhdanh080200** [skeletonlabs/skeleton#2487] opened 2024-02-16 07:26 UTC
### Current Behavior

I have an input and an autocomplete popup. When I click on input, the autocomplete popup shows below the input (image below).
![current](https://github.com/skeletonlabs/skeleton/assets/49565984/685ba41c-daa1-40c2-9b99-4ff2e694c57a).

However, the popup isn't align correctly with input.

### Expected Behavior

I would like the popup is align with input like the image below (the red line)
![exptect](https://github.com/skeletonlabs/skeleton/assets/49565984/c4ae0b41-7109-4842-a594-76b5e15aeb80)

### Steps To Reproduce

Here is my code: 
```ts
<script lang="ts">
	import {
		Autocomplete,
		popup,
		type PopupSettings,
		type AutocompleteOption,
	} from '@skeletonlabs/skeleton';

	type FlavorOption = AutocompleteOption<string, { healthy: boolean }>;
	const flavorOptions: FlavorOption[] = [
		{ label: 'Vanilla', value: 'vanilla', keywords: 'plain, basic', meta: { healthy: false } },
		{ label: 'Chocolate', value: 'chocolate', keywords: 'dark, white', meta: { healthy: false } },
		{ label: 'Strawberry', value: 'strawberry', keywords: 'fruit', meta: { healthy: true } },
		{
			label: 'Neapolitan',
			value: 'neapolitan',
			keywords: 'mix, strawberry, chocolate, vanilla',
			meta: { healthy: false },
		},
		{ label: 'Pineapple', value: 'pineapple', keywords: 'fruit', meta: { healthy: true } },
		{ label: 'Peach', value: 'peach', keywords: 'fruit', meta: { healthy: true } },
	];

	let popupSettings: PopupSettings = {
		event: 'focus-click',
		target: 'popupAutocomplete',
		placement: 'bottom',
	};

	let inputPopupDemo = '';
	function onPopupDemoSelect(event: CustomEvent<FlavorOption>): void {
		inputPopupDemo = event.detail.label;
	}
</script>

<div class="text-token w-96 space-y-2">
	<input
		class="autocomplete input"
		type="search"
		name="autocomplete-search"
		bind:value={inputPopupDemo}
		placeholder="Search..."
		use:popup={popupSettings} />
	<div data-popup="popupAutocomplete" class="card w-96 overflow-y-auto" tabindex="-1">
		<Autocomplete
			bind:input={inputPopupDemo}
			options={flavorOptions}
			on:selection={onPopupDemoSelect} />
	</div>
</div>
```

**Comment by endigo9740** [comment] 2024-02-16 07:49
@vuthanhdanh080200 so in your screenshot it looks like your trigger element is very close to the edge of the visible screen. This is notable because Floating UI provides several middleware options for controlling position, including one called shift:
https://floating-ui.com/docs/shift

We utilize this in the popup's default settings, which you can see here:
https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/utilities/Popup/popup.ts#L59

This essentially sets a padding offset of 8px away from the edge of the screen, so it will never be flush like you may be expecting. This is configurable though, which we cover in the Middleware docs here:
https://www.skeleton.dev/utilities/popups#middleware

Feel free to adjust as needed.

Given this is intended behavior, not a bug, I'll go ahead and close this issue. But if you any follow up questions, feel free to reach out and I'll respond (though it may be tomorrow my time).

**Closed by endigo9740** 2024-02-16 07:49 UTC
Labels: bug

**Comment by vuthanhdanh080200** [comment] 2024-02-16 11:45
It's working now. Thank you for your fastly answer @endigo9740. Here is my code for anyone needed.

```ts
<script lang="ts">
	import {
		InputChip,
		Autocomplete,
		popup,
		type PopupSettings,
		type AutocompleteOption,
	} from '@skeletonlabs/skeleton';
	import type { SizeOptions } from '@floating-ui/dom';

	import { uniqueId } from 'lodash';

	let inputChip = '';
	let inputChipList = ['vanilla', 'chocolate'];
	type FlavorOption = AutocompleteOption<string, { healthy: boolean }>;
	const flavorOptions: FlavorOption[] = [
		{ label: 'Vanilla', value: 'vanilla', keywords: 'plain, basic', meta: { healthy: false } },
		{ label: 'Chocolate', value: 'chocolate', keywords: 'dark, white', meta: { healthy: false } },
		{ label: 'Strawberry', value: 'strawberry', keywords: 'fruit', meta: { healthy: true } },
		{
			label: 'Neapolitan',
			value: 'neapolitan',
			keywords: 'mix, strawberry, chocolate, vanilla',
			meta: { healthy: false },
		},
		{ label: 'Pineapple', value: 'pineapple', keywords: 'fruit', meta: { healthy: true } },
		{ label: 'Peach', value: 'peach', keywords: 'fruit', meta: { healthy: true } },
	];

	function onInputChipSelect(event: CustomEvent<FlavorOption>): void {
		console.log('onInputChipSelect', event.detail);
		if (inputChipList.includes(event.detail.value) === false) {
			inputChipList = [...inputChipList, event.detail.value];
			inputChip = '';
		}
	}

	const uuid = uniqueId('multiple-select-popup');

	let popupSettings: PopupSettings = {
		event: 'focus-click',
		target: uuid,
		placement: 'bottom-start',
		middleware: {
			shift: {
				padding: 0,
			},
			offset: 0,
			size: {
				apply({ rects, elements }) {
					Object.assign(elements.floating.style, {
						width: `${rects.reference.width}px`,
					});
				},
			} as SizeOptions,
		},
	};
</script>

<div use:popup={popupSettings} class="w-full">
	<InputChip bind:input={inputChip} bind:value={inputChipList} name="chips" />
	<div data-popup={popupSettings.target} class={`card max-h-48  overflow-y-auto`} tabindex="-1">
		<Autocomplete
			bind:input={inputChip}
			options={flavorOptions}
			denylist={inputChipList}
			on:selection={onInputChipSelect} />
	</div>
</div>
```
