### ISSUE TITLE
Drawer animation direction is wrong in a rtl page

### ISSUE THREAD

**Issue by LoremFooBar** [skeletonlabs/skeleton#2344] opened 2023-12-21 14:46 UTC
### Current Behavior

The drawer animation direction is wrong in a page where `dir="rtl"` is specified.

### Expected Behavior

The drawer animation should respect the `dir` attribute.

### Steps To Reproduce

1. Add a drawer.
2. Set `dir="rtl"` on any parent of a drawer.
3. Open/close the drawer.

### Link to Reproduction / Stackblitz

https://github.com/LoremFooBar/SkeletonDrawerRtlAnimationIssue

### More Information

The workaround I found is to invert the direction of the drawer and invert back the direction of the contents:

```svelte
<!-- app.html -->
<html dir="rtl">

<!-- +layout.svelte -->
<span dir="ltr">
  <Drawer width="w-fit">
     <span dir="rtl">
       {#if $drawerStore.id === "app-sidebar"}
         <Sidebar />
       {/if}
     </span>
  </Drawer>
</span>
```

**Comment by Sarenor** [comment] 2023-12-21 15:17
Yeah, sadly Skeleton isn't quite as RTL friendly as we'd like right now.

The good news is that work on Version 3 has started and LTR/RTL, css logical properties are very high on the list of things to keep in mind: https://github.com/skeletonlabs/skeleton/issues/2314

**Comment by endigo9740** [comment] 2023-12-21 15:17
Duplicate of: https://github.com/skeletonlabs/skeleton/issues/2314

@LoremFooBar we intend to address LTR/RTL support in Skeleton v3. So this would be considered a feature request for that upcoming version. As such I'm going to mark this as a duplicate for that effort. Thanks!

**Closed** 2023-12-21 15:17 UTC
Labels: bug

**Comment by LoremFooBar** [comment] 2023-12-21 15:25
Great, looking forward to v3. Though I have to say Skeleton's current RTL support is pretty good because that's the only issue I found so far.
