### ISSUE TITLE
Error starting new project - `@layer base` is used but no matching `@tailwind base` directive is present.

### ISSUE THREAD

**Issue by JWeis** [skeletonlabs/skeleton#1731] opened 2023-07-06 12:29 UTC
### Current Behavior

Upon running the dev server, I receive this error: 

```
[plugin:vite:css] [postcss] postcss-import: /Users/jamesweis/Projects/Cove/cove-svelte/node_modules/@skeletonlabs/skeleton/dist/styles/partials/core.css:3:1: `@layer base` is used but no matching `@tailwind base` directive is present.
/Users/jamesweis/Projects/Cove/cove-svelte/node_modules/@skeletonlabs/skeleton/dist/styles/partials/core.css:3:1
1  |  /* Stylesheet: skeleton.css */
2  |  
3  |  /*
   |   ^
4  |  - Slated to replace `all.css` in the next major release
5  |  - All available stylesheets are imported
CssSyntaxError: [postcss] postcss-import: /Users/jamesweis/Projects/Cove/cove-svelte/node_modules/@skeletonlabs/skeleton/dist/styles/partials/core.css:3:1: `@layer base` is used but no matching `@tailwind base` directive is present.
    at Input.error (/Users/jamesweis/Projects/Cove/cove-svelte/node_modules/postcss/lib/input.js:106:16)
    at AtRule.error (/Users/jamesweis/Projects/Cove/cove-svelte/node_modules/postcss/lib/node.js:115:32)
    at normalizeTailwindDirectives (/Users/jamesweis/Projects/Cove/cove-svelte/node_modules/tailwindcss/lib/lib/normalizeTailwindDirectives.js:72:32)
    at /Users/jamesweis/Projects/Cove/cove-svelte/node_modules/tailwindcss/lib/processTailwindFeatures.js:30:98
    at plugins (/Users/jamesweis/Projects/Cove/cove-svelte/node_modules/tailwindcss/lib/plugin.js:38:63)
    at LazyResult.runOnRoot (/Users/jamesweis/Projects/Cove/cove-svelte/node_modules/postcss/lib/lazy-result.js:357:16)
    at LazyResult.runAsync (/Users/jamesweis/Projects/Cove/cove-svelte/node_modules/postcss/lib/lazy-result.js:286:26)
    at LazyResult.async (/Users/jamesweis/Projects/Cove/cove-svelte/node_modules/postcss/lib/lazy-result.js:160:30)
    at LazyResult.then (/Users/jamesweis/Projects/Cove/cove-svelte/node_modules/postcss/lib/lazy-result.js:436:17
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```

```running

### Expected Behavior

To build an run without errors.

### Steps To Reproduce

1. Follow the current CLI installation instruction OR
2. Follow the Manual installation instructions

### Link to Reproduction / Stackblitz

_No response_

### More Information

_No response_

**Comment by Sarenor** [comment] 2023-07-06 12:32
We figured it out on Discord:
https://discord.com/channels/1003691521280856084/1126456275409047613

Layout.svelte:
```html
<script lang='ts'>
    // Most of your app wide CSS should be put in this file
    import '../app.postcss';
</script>

<slot />
```
app.postcss:
```css
@import '@skeletonlabs/skeleton/themes/theme-skeleton.css';

@tailwind base;
@tailwind components;
@tailwind utilities;
@tailwind variants;


@import '@skeletonlabs/skeleton/dist/styles/partials/core.css';
@import '@skeletonlabs/skeleton/dist/styles/partials/typography-next.css';
@import '@skeletonlabs/skeleton/dist/styles/partials/elements.css';
@import '@skeletonlabs/skeleton/dist/styles/partials/variants.css';

    /*place global styles here */
html,
body {
    @apply h-full;
}
```
Basically, there's something broken with importing stylesheets that then activate the ``@tailwind`` layers and if you do it yourself and "re-create" the ``skeleton.css`` file in your own app.postcss you should be good.

Sorry for any inconvenience and we're working on finding & fixing the cause of this issue

**Comment by JWeis** [comment] 2023-07-06 12:35
@Sarenor thank you so much for the quick response! I can also confirm I am getting the same error in versions 1.8.0 and 1.7.0

**Comment by JWeis** [comment] 2023-07-06 12:58
@Sarenor It is working now. Getting a lot of warnings in the console for the placement of @imports, but it is working. Thank you!

**Comment by Sarenor** [comment] 2023-07-06 13:26
@JWeis Better fix: Downgrade Vite to 4.3.9.

**Comment by JWeis** [comment] 2023-07-06 13:59
@Sarenor, I had Vite 4.3.6 installed as the default. I upgraded to 4.4.0, and it seems to work inline with the current documentation.

**Comment by Sarenor** [comment] 2023-07-06 14:07
Huh. Alright, re-adding the fix documentation then. Although downgrading it did fix it for me without having to build the ``skeleton.css`` myself.

**Comment by johannesbremer** [comment] 2023-07-06 14:08
downgrading fixed it for me as well!

**Comment by Sarenor** [comment] 2023-07-06 16:54
Relevant Issue raised with vite: https://github.com/vitejs/vite/issues/13732

**Comment by JWeis** [comment] 2023-07-06 18:54
@Sarenor it is working better for me with vite 4.3.9. For some reason, 4.4.0 was working on my test project and then I tried it on a fresh project and I was getting the original error. I just switch to 4.3.9 and it is working as I would expect. Thank you!

**Comment by endigo9740** [comment] 2023-07-06 21:30
Just so everyone is aware - we believe the issue to be on Vite's side per the issue @Sarenor raised above. We're monitoring to see how they address. In the meantime we do advise sticking with Vite v4.3.9 for now. Keep an eye on this post and we'll update when we know more.

**Comment by Sarenor** [comment] 2023-07-07 06:47
Vite's got a PR open for it already. Seems like we're on the way to a resolution there :)

**Comment by Sarenor** [comment] 2023-07-07 10:34
Fixed with ``"vite": "4.4.2"``
New projects should be safe again!

**Closed by Sarenor** 2023-07-07 10:34 UTC
Labels: bug

**Comment by johannesbremer** [comment] 2023-07-07 11:23
This works for me. Thank you for all your work!

**Comment by Sarenor** [comment] 2023-07-07 11:27
Of course. Telling other people that it's their problem is my favorite part of work! ;)
