### ISSUE TITLE
Internal server error: Missing "./index.js" specifier in "@skeletonlabs/skeleton" package

### ISSUE THREAD

**Issue by TimotheFCN** [skeletonlabs/skeleton#1774] opened 2023-07-18 22:27 UTC
### Current Behavior

I get this weird error when trying to load a page using any of the skeleton components in my project:
`Internal server error: Missing "./index.js" specifier in "@skeletonlabs/skeleton" package`

I have followed the manual install guide.

### Expected Behavior

This error should not appear and the page should load.

### Steps To Reproduce

1. Install Skeleton manually
2. Use the Table component for exemple (<Table source={camTable} />) inside a page.

**Comment by endigo9740** [comment] 2023-07-19 02:40
@TimotheFCN unfortunately I'm not sure there's enough info for us to troubleshoot here. Would you be able to share a minimal reproduction?

Also what version of Skeleton are you running? Skeleton v1.10.0 dropped earlier today so even if you installed today we'll need to know which version you landed on.

**Comment by endigo9740** [comment] 2023-08-04 20:16
None of the quested information was provided, so closing due to inactivity. Happy to reopen if this is provided.

**Closed by endigo9740** 2023-08-04 20:16 UTC
Labels: bug
