### ISSUE TITLE
Popup state called repeatedly when inside #each block

### ISSUE THREAD

**Issue by saturnonearth** [skeletonlabs/skeleton#1323] opened 2023-04-14 01:18 UTC
### Current Behavior

I am creating a dropdown. It will popup for each card, because each card has a vertical ellipsis that you can click to see additional options. I have one set of PopupSettings and one target. When inside the #each block, the state seems to be called for every single popup at once, making it so it closes instantly.

### Steps To Reproduce

1. Create 1 popup settings, console.log state
2. Create one popup target
3. Create #each block and place use:popup on a button inside the #each

### Anything else?

Not sure if this is duplicate to issue #1305

**Comment by Sarenor** [comment] 2023-04-14 06:05
Can you provide a minimum reproduction or your sample code?
With just this I couldn't recreate your issue and I'd rather see the source than guessing around:
```html
<div class="flex flex-col w-full h-full m-4 mt-9">	
        <script lang="ts">
	        import { popup, type PopupSettings } from "@skeletonlabs/skeleton";
        
	        let focusPopup = {
		        event: 'focus',
		        target: 'focus'
	        };
        </script>
	<div data-popup="focus" class="card variant-filled p-4">Click outside to close.</div>

	<button class="button" use:popup={focusPopup}>One</button>
	<button class="button" use:popup={focusPopup}>Two</button>
	<button class="button" use:popup={focusPopup}>Three</button>
</div>
```

**Comment by saturnonearth** [comment] 2023-04-14 15:06
> Can you provide a minimum reproduction or your sample code? With just this I couldn't recreate your issue and I'd rather see the source than guessing around:
>

I believe it's partly due to the event being a "click" event.

Here is my example:

```html
<script lang="ts">
    import { popup,type PopupSettings  } from "@skeletonlabs/skeleton";

    let focusPopup: PopupSettings = {
        event: 'click',
        target: 'popupElem',
	placement: 'bottom',
	state: (e) => console.log(e)
    };

const posts = [
    {
      "id": 1,
      "title": "10 Tips for Successful Time Management",
      "author": "Jane Smith",
      "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus eget enim fringilla tristique a a nulla. Nam eu est vel eros finibus ullamcorper non eu nibh. Sed auctor euismod risus, eu bibendum elit iaculis nec. Donec efficitur eros non erat bibendum, quis fermentum nunc venenatis. Duis vel massa magna. ",
      "date_posted": "2022-02-10"
    },
    {
      "id": 2,
      "title": "How to Start Your Own Business",
      "author": "John Doe",
      "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus eget enim fringilla tristique a a nulla. Nam eu est vel eros finibus ullamcorper non eu nibh. Sed auctor euismod risus, eu bibendum elit iaculis nec. Donec efficitur eros non erat bibendum, quis fermentum nunc venenatis. Duis vel massa magna.",
      "date_posted": "2022-03-15"
    },
    {
      "id": 3,
      "title": "The Benefits of Yoga for Stress Relief",
      "author": "Sarah Johnson",
      "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus eget enim fringilla tristique a a nulla. Nam eu est vel eros finibus ullamcorper non eu nibh. Sed auctor euismod risus, eu bibendum elit iaculis nec. Donec efficitur eros non erat bibendum, quis fermentum nunc venenatis. Duis vel massa magna. ",
      "date_posted": "2022-04-01"
    }
];

</script>
<div class="flex flex-col w-full h-full gap-y-4 max-w-sm m-4 mt-9">	

	{#each posts as post (post.id)}
		<button class="btn variant-ghost-primary btn-sm" use:popup={focusPopup}>{post.title}</button>
	{/each}
</div>


<div data-popup="popupElem" class="card variant-filled p-4">Click outside to close.</div>
```

**Comment by Sarenor** [comment] 2023-04-17 10:35
I haven't had the time to dive into popups to explain to you why it is a problem, but you can't re-use the same data-popup element like that, because it will always try to attach itself to the most recent call to popups.

To fix that, you can easily change your code like so:
```html
<script lang="ts">
    import { popup,type PopupSettings  } from "@skeletonlabs/skeleton";

    let focusPopup = {
        event: 'click',
		placement: 'bottom',
		state: (e) => console.log(e)
    };

const posts = [
    {
      "id": 1,
      "title": "10 Tips for Successful Time Management",
      "author": "Jane Smith",
      "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus eget enim fringilla tristique a a nulla. Nam eu est vel eros finibus ullamcorper non eu nibh. Sed auctor euismod risus, eu bibendum elit iaculis nec. Donec efficitur eros non erat bibendum, quis fermentum nunc venenatis. Duis vel massa magna. ",
      "date_posted": "2022-02-10"
    },
    {
      "id": 2,
      "title": "How to Start Your Own Business",
      "author": "John Doe",
      "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus eget enim fringilla tristique a a nulla. Nam eu est vel eros finibus ullamcorper non eu nibh. Sed auctor euismod risus, eu bibendum elit iaculis nec. Donec efficitur eros non erat bibendum, quis fermentum nunc venenatis. Duis vel massa magna.",
      "date_posted": "2022-03-15"
    },
    {
      "id": 3,
      "title": "The Benefits of Yoga for Stress Relief",
      "author": "Sarah Johnson",
      "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus eget enim fringilla tristique a a nulla. Nam eu est vel eros finibus ullamcorper non eu nibh. Sed auctor euismod risus, eu bibendum elit iaculis nec. Donec efficitur eros non erat bibendum, quis fermentum nunc venenatis. Duis vel massa magna. ",
      "date_posted": "2022-04-01"
    }
];

</script>
<div class="flex flex-col w-full h-full gap-y-4 max-w-sm m-4 mt-9">	
	{#each posts as post (post.id)}
		<button class="btn variant-ghost-primary btn-sm" use:popup={{...focusPopup, target: `popupElement-${post.id}`}}>{post.title}</button>
	{/each}
</div>


{#each posts as post (post.id)}
	<div data-popup={`popupElement-${post.id}`} class="card variant-filled p-4">Click outside to close.</div>
{/each}
```

**Comment by saturnonearth** [comment] 2023-04-17 23:06
That is rather unfortunate. I would need to either create a "fake" initial target or @ts-ignore the TS error from lack of a target in the initial settings.

Hopefully this can be resolved in a future update to popups :)

**Comment by Sarenor** [comment] 2023-04-18 05:12
There's certainly a lot of thinking/conversation going on about future popup updates right now.
We'll see what we can do I guess!

**Comment by saturnonearth** [comment] 2023-04-24 15:32
To update on this, I implemented @Sarenor's suggestion and it works great! I looked back and I actually did this a similar way using svelte's version of headless-ui. My only concern (along with what I said above about Typescript), was that creating the popup element repeatedly would result in a lot of unneeded bulk to the compiled code, and in the future, I may need to do this on a bigger scale, so the worry grows. But I don't actually know how the end-code is compiled, and I my worry may be mis-placed. Hopefully that makes sense?

**Comment by Sarenor** [comment] 2023-04-25 05:11
I haven't taken a look into how Svelte compiles actions to be honest.
But I assume since it's just a function that receives a HtmlNode and the action parameter, I'd assume that if you use it it's included once and can be called from everywhere:
https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/utilities/Popup/popup.ts#L14
At least that'd make sense to me?

**Comment by endigo9740** [comment] 2023-05-03 20:28
@Sarenor @Sarenor I was reviewing this as part of the new popup refactor. I've tested this with all current updates and currently this functions the same way. The action expects a unique element reference to be passed. To put it another way, the trigger and popup are a pair and you need one instance of either at any given time.

That said, I think Sarenor's approach here is still the best, though I'd recommend co-locating the button/popup within the same each block so everything is generated in one go.

```html
<section class="grid grid-cols-3 gap-4">
	{#each posts as post (post.id)}
		<button class="btn variant-soft" use:popup={{ event: 'hover', target: `popupEachTest-${post.id}` }}>{post.author}</button>
		<div data-popup="popupEachTest-{post.id}" class="card variant-filled p-4 z-10">
			<div>{post.title}</div>
			<div class="arrow variant-filled" />
		</div>
	{/each}
</section>
```

Since you mentioned your concern is performance, let me explain a bit about how this works and where your bottlenecks might be.

1. Currently even if we had a means to share a single popup element between multiple triggers, you would still have multiple instance of the Action function. This is required because each one needs to "think for itself" and understand the rules for how it should interact with the popup itself.
2. Your popup element is not going to going to have a huge overhead - it's just HTML/CSS with a data attribute on it so the action can target it. Your only bottleneck here is how well the page performance with X many divs (or whatever contents are rendered within). Though by default these should all be hidden on load via our CSS.
3. Return to the action, we're actually pretty lean in what sorts of calculations are running. Per a previous update I implemented a change that only allows Floating UI to recalculate the position WHILE a popup is open. Logically this will typically only happen for one popup on screen at a time. That said we do calculate position on init per each action, when the open method is called, and when Floating UI's update method runs (again, only while open)
4. Really the biggest concern here is having X number of event listeners on the page. We have three event listeners per any event type (ex: click, hover, focus). This includes the open listener, the close listener, and keypress listener. So three event listeners per instance if you will.

It might be researching to determine if there's a recommended max for event listeners per a single page on a browser, then you know where your max popups allowed falls. But in most cases I think modern browser manage these well. And of course, it goes without saying, but we clean these up when the action element is destroyed - say when changing to another page.

That said, not to miss the forest for the trees here, you might make considerations whether popups/tooltips are the best way to handle your interface. Does this HAVE to be a floating element or can it be a dynamic element that just shows/hides on a fix portion of the page? These are always going to be concerns when following good UX practices. Everything has a cost, whether it's the popups or not. So make sure you determine what your options are here.

This said, I'm going to close this issue as I don't believe there's any more we can do with this iteration with the popup. We do plan to pull certain utility features out of the core in the future. When we do that we might investigate another ways for improving performance. But for now I think we've done all we can!

**Comment by endigo9740** [comment] 2023-05-03 20:30
Also, random performance tip - avoid CSS at all costs when you're iterating a lot of items. This adds up and will have a notable performance hit. Keep your popup elements as simple as possible!

**Comment by saturnonearth** [comment] 2023-05-03 20:41
Thanks for the explanation. I will look into the event listeners.

> avoid costly CSS like shadows at all costs when you're iterating a lot of items.

Interesting...thanks!

**Comment by endigo9740** [comment] 2023-05-03 22:51
Given we've now settled on an official recommendation and suggestion here, but not changes are implemented into the popup action, I'm going to go ahead and mark this closed and complete. Thanks!

**Closed by endigo9740** 2023-05-03 22:51 UTC
Labels: bug
