### ISSUE TITLE
Docs states that Drawers has props not actually available

### ISSUE THREAD

**Issue by centomila** [skeletonlabs/skeleton#2866] opened 2024-09-28 03:52 UTC
### Link to the Page

https://www.skeleton.dev/utilities/drawers?tab=properties

### Describe the Issue (screenshots encouraged!)

DrawerSettings type contains those props
```
export interface DrawerSettings {
    open?: boolean;
    /** A unique identifier, useful for setting contents. */
    id?: string;
    /** Pass arbitrary information for your own persona use. */
    meta?: any;
    /** Set the anchor position.
     * @type {'left' | 'top' | 'right' | 'bottom'}
     */
    position?: 'left' | 'top' | 'right' | 'bottom';
    /** Backdrop - Provide classes to set the backdrop background color*/
    bgBackdrop?: string;
    /** Backdrop - Provide classes to set the blur style.*/
    blur?: string;
    /** Drawer - Provide classes to set padding.*/
    padding?: string;
    /** Drawer - Provide classes to set the drawer background color.*/
    bgDrawer?: string;
    /** Drawer - Provide classes to set border color.*/
    border?: string;
    /** Drawer - Provide classes to set border radius.*/
    rounded?: string;
    /** Drawer - Provide classes to set box shadow.*/
    shadow?: string;
    /** Drawer - Provide classes to override the width.*/
    width?: string;
    /** Drawer - Provide classes to override the height.*/
    height?: string;
    /** Define the Svelte transition animation duration.*/
    duration?: number;
    /** Drawer - Enable/Disable opacity transition */
    opacityTransition?: boolean;
    /** Provide arbitrary classes to the backdrop region. */
    regionBackdrop?: string;
    /** Provide arbitrary classes to the drawer region. */
    regionDrawer?: string;
    /** Provide an ID of the element labeling the drawer.*/
    labelledby?: string;
    /** Provide an ID of the element describing the drawer.*/
    describedby?: string;
}
```

zIndex is not available as stated in the documentation.

I don't know if the error is in the documentation or if it's a bug in the code in the Drawer component.

![image](https://github.com/user-attachments/assets/f1e2b18c-5125-44cd-85b2-b4af6a6219b7)

**Comment by endigo9740** [comment] 2024-09-28 04:34
@centomila the interface you've included here are not related to props. They're programmatic settings passed when triggering a drawer. Two separate things.

Here's an example of prop usage:
```html
<Drawer padding="p-10" />
```

And here's an example of `DrawerSettings`:
```ts
const drawerSettings: DrawerSettings = {
	// ...
	bgDrawer: 'bg-green-500'
};
drawerStore.open(drawerSettings);
```

Props are great when you want to set default values for all instances of the Drawer (ex: always have X color background). While `DrawerSettings` are set per each time a drawer is opened. It's mirroring the same pattern we use for Modals.

I'll go ahead and close this as everything is working as intended. But feel free to respond if I can clarify anything.

**Closed by endigo9740** 2024-09-28 04:34 UTC
Labels: documentation

**Comment by centomila** [comment] 2024-09-28 14:03
Sorry 😔. I saw some properties like _bgBackdrop_ in _DrawerSettings_ and _Drawer_ were the same, and I mistakenly thought that the norm was they needed to always be available in both. 

Thanks for your assistance.

**Comment by endigo9740** [comment] 2024-09-28 17:35
No worries, easy mistake to make. That's why we're here to help! :)
