### ISSUE TITLE
A little bit of white peeking out on the progress bars (styling issue)

### ISSUE THREAD

**Issue by bn-l** [skeletonlabs/skeleton#2736] opened 2024-06-26 09:25 UTC
### Current Behavior

![Screenshot 2024-06-26 192252](https://github.com/skeletonlabs/skeleton/assets/13162197/8837022d-f76c-42a4-8c8d-8d38caf3688f)

### Expected Behavior

No white bits poking out

### Steps To Reproduce

1. Use the progress bar as described on the svelte demo page: https://www.skeleton.dev/components/progress-bars 
(screen shot was taken from this demo)

### Link to Reproduction / Stackblitz

https://www.skeleton.dev/components/progress-bars

**Comment by endigo9740** [comment] 2024-06-26 14:13
Hey @bn-l can you confirm what OS/browser combination you're using so we can attempt to reproduce this? I'm not able to reproduce the issue on Chrome on Mac OS.

Also, can you confirm if the issue is present for you on the Skeleton v3's iteration:
https://next.skeleton.dev/docs/components/progress/svelte/

**Comment by bn-l** [comment] 2024-06-27 04:12
Sorry,

Machine:
Win 10, 22H2

Browser: 
Version 126.0.6478.114 (Official Build) (64-bit)

Resolution:
1920x1080

Confirmed resolved on Skeleton v3 (https://next.skeleton.dev/docs/components/progress/svelte/):

![image](https://github.com/skeletonlabs/skeleton/assets/13162197/c8e9d614-0742-4cd0-b4fc-7c0b9fd05d3a)

**Comment by endigo9740** [comment] 2024-07-17 20:17
@bn-l just FYI I tried to reproduce on my Windows 10 PC w/ Chrome (Latest) and unfortunately I'm not seeing this. Even if I zoom way in:

![image](https://github.com/user-attachments/assets/4f6559e7-8cb1-4906-8aee-9baf76979213)

Can you share any other details that might help here:

1. Is this a Skeleton or custom theme?
2. The progress bar looks to be on a dark background in light mode, correct?
3. Have you applied any custom classes via props or is it stock settings?
4. The meter looks to be empty, is the value set to `0`?

Unfortunately I'm not sure what else we can do here. I know it's a fairly small issue, so if you're good with it we might close this in favor of just waiting for the fix in v3.

**Comment by bn-l** [comment] 2024-07-21 11:59
Now I can't reproduce it myself (same environment as when issue was created). 

> Unfortunately I'm not sure what else we can do here. I know it's a fairly small issue, so if you're good with it we might close this in favor of just waiting for the fix in v3.

Sounds good. If I see it again I'll reopen with a much more detailed issue.

**Closed** 2024-07-21 12:00 UTC
Labels: bug
