### ISSUE TITLE
Rename References of "Blacklist" and "Whitelist" to "BlockList" and "AllowList"

### ISSUE THREAD

**Issue by jbfbell** [skeletonlabs/skeleton#1298] opened 2023-04-08 16:19 UTC
### Current Behavior

Currently the [Autocomplete Component](https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/components/Autocomplete/Autocomplete.svelte) uses the variable names `blacklist` and `whitelist`.

These terms are antiquated and rooted in American racism. "BlockList" and "AllowList" are new industry standard terms and are also more descriptive about their intended purpose.

### Steps To Reproduce

1. https://www.skeleton.dev/components/autocomplete
2. Search page for blacklist or whitelist

**Comment by jbfbell** [comment] 2023-04-08 16:26
Created the PR #1299

**Comment by jbfbell** [comment] 2023-04-08 17:25
Ah I see the comments in the code that these are already slated to be removed in favor of `allowlist` and `denylist`. I didn't see an issue for it so feel free to use this one or close it.

**Comment by endigo9740** [comment] 2023-04-08 17:39
Duplicate of: https://github.com/skeletonlabs/skeleton/issues/1276

**Closed by endigo9740** 2023-04-08 17:39 UTC
Labels: bug
