### ISSUE TITLE
Carousels example

### ISSUE THREAD

**Issue by yacinecheikh** [skeletonlabs/skeleton#2756] opened 2024-07-13 12:16 UTC
### Link to the Page

https://www.skeleton.dev/elements/scroll-containers

### Describe the Issue (screenshots encouraged!)

This code:
```js
function carouselLeft(): void {
	const x =
		elemCarousel.scrollLeft === 0
			? elemCarousel.clientWidth * elemCarousel.childElementCount // loop
			: elemCarousel.scrollLeft - elemCarousel.clientWidth; // step left
	elemCarousel.scroll(x, 0);
}
```
with this code:
```html
<div bind:this={elemCarousel} …
```

when together, will try to scroll x to (the width of the entire carousel * the number of elements).
I cannot reliably confirm that the code does not work because the example does not seem to be scrolling at all in my browser (Librewolf), but this code did not work in my own website (the left button would always switch between the left and the right with no in-between).

I think `elemCarousel` is supposed to be an item in the Carousel, since this should fix the formula (it did in my own website, but with an other layout).

I have not checked the other scroll container examples in detail because I had to change both the formulas and the layout in order to have the expected behaviour on my own website.

**Comment by yacinecheikh** [comment] 2024-07-13 12:17
I just checked the existing issues, my problem may just be a duplicate of #2731

**Comment by endigo9740** [comment] 2024-07-13 18:04
@yacinecheikh in #2731 the issue is the image source we were using has stopped working. Those images need to be replaced. However the carousel should be fully functional with working images, similar to our other example:

https://www.skeleton.dev/elements/scroll-containers#multicolumn

I've never heard of Librewolf, but checking their site it seems to be based on Firefox. It should render and operate the same as Firefox does, and we have done extensive cross browser testing on this feature.

The team and I have [shifted our focus ) to Skeleton v3](https://github.com/skeletonlabs/skeleton/discussions/2729, so I'm going to do two things - close this issue as a duplicate, ask that you consider sending a PR to resolve the images as we don't have the bandwidth right now.

I will call this out to the team though as it should be an easy fix. Maybe one of them will have a chance to jump on it soon.

**Closed by endigo9740** 2024-07-13 18:04 UTC
Labels: documentation
