### ISSUE TITLE
Props not working as expected on InputChip & AutoComplete combination

### ISSUE THREAD

**Issue by uncapped1599** [skeletonlabs/skeleton#2293] opened 2023-12-07 05:39 UTC
### Current Behavior

The combination of InputChip, AutoComplete & Popup is working generally as expected but it appears the `max={3}` prop does not apply, and the `whitelist` prop does not parse the values or labels correctly. It blocks all input even if it matches underlying data. 

### Expected Behavior

I believe as outlined in the docs, the `max` prop should not allow anymore input chips to be added after the defined number and the `whitelist` prop should allow adding of values that match the passed in array. 

### Steps To Reproduce

1. Create InputChip and Autocomplete combination
2. Pass in array of values in expected `value:x, label:y` format for the search values
3. Manually select values or search and add
4. When you add more than the max chips, it does not change behaviour.
5. Also, adding a value from the array triggers invalidation

Here is my code snippet to re-create the issue. The `rates` array is in the stackblitz.

```
<div class="text-token w-full max-w-lg space-y-2 mt-2" use:popup={popupSettings}>
  <InputChip
    bind:input={inputChip}
    bind:value={inputChipList}
    name="rates"
    max={3}
    placeholder="Enter currencies..."
  />
  <div class="card w-full max-w-lg max-h-48 px-4 overflow-y-auto" tabindex="-1" data-popup="popupAutocomplete">
    <Autocomplete
      bind:input={inputChip}
      options={rates}
      denylist={inputChipList}
      on:selection={onInputChipSelect}
    />
  </div>
</div>
```

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/jq-starter-4irrwr?file=my-skeleton-app%2Fsrc%2Froutes%2F%2Bpage.svelte

### More Information

Thanks for all your hard work on the Skeleton project, it really is great!

**Comment by Mahmoud-zino** [comment] 2023-12-14 19:27
@uncapped1599 both props are working as expected, so I will break down the problems you are facing:
## whitelist
the whitelist prop on the Input chip is expecting a `string[]`, but you are trying to filter with an object `{ label: string, value: string}[]`.
so to solve this issue you can do something like:
```ts
<InputChip
	...
	whitelist={rates.map(r => r.value)}
/>
```
as for why the selection is working even that the whitelist doesn't allow it, see below
## max
The max property is working as expected, however the problem is that when you change the input yourself, the inputChip is not being validated, so both max and whitelist are not being checked.
the real bug in the implementation is that at the moment there is no way to validate the inputChip yourself.

## solution
we could add tow new exported methods (addChip, removeChip) which will get the chip as string to add/remove them and validate only when adding new chips.
Users can then bind the InputChip component itself and call both functions when needed.
I would need your confirmation before implementing it @endigo9740

**Comment by endigo9740** [comment] 2023-12-14 20:45
@Mahmoud-zino sorry to sound like a broken record, but let me review this in depth next week. I'll be combing through all pending bug tickets and creating minimal reproductions to understand the issue directly. I can then provide an informed opinion on how we should proceed. Thanks!

**Comment by uncapped1599** [comment] 2023-12-15 07:36
@Mahmoud-zino thanks for that response and for catching my silly mistake on the whitelist. Can confirm that works, after a bit more mutating of the array to capture both rate.value & rate.label and checking for case. 

Thanks to both of @endigo9740 & @Mahmoud-zino for exploring the issue. Look forward to all improvements from you!

**Comment by Mahmoud-zino** [comment] 2023-12-18 18:36
@endigo9740 I think the preproduction provided in the issue should suffice, you can head to the ` +page.svelte`  and check the function `onInputChipSelect`  where the user is trying to change the input-chips manually (add or remove) but can't call the submit therefore can't validate the chips.

**Comment by endigo9740** [comment] 2023-12-20 22:25
@uncapped1599 per your last response it sounds like this issue was resolved, so I'll go ahead and close this out. Happy to reopen if that's not the case though!

**Comment by Mahmoud-zino** [comment] 2023-12-21 10:35
@endigo9740 one of the tow issues is solved, the other one (users should be able to manually add/remove chips) should still be handled, I had already provided a way to solve this just needed your confirmation...

**Comment by endigo9740** [comment] 2023-12-21 15:20
Sure @Mahmoud-zino, given there will likely be substantial changes to this feature in v3 then you're welcome to handle this as desired in v2. I like the proposed solution. Send a PR and I'll review asap!

**Closed** 2024-01-29 18:09 UTC
Labels: bug
