### ISSUE TITLE
Popup: Difference in behaviour between hover, and hover-click

### ISSUE THREAD

**Issue by DevOfManyThings** [skeletonlabs/skeleton#1316] opened 2023-04-12 15:35 UTC
### Current Behavior

If an element has `hover-click` as the `event` for https://www.skeleton.dev/utilities/popups, it renders correctly when the mouse hovers over it, but doesn't remove itself when the mouse hovers away, it requires a click elsewhere to remove itself.

Compared to the smoothness of `hover` and `click` events which can be seen on the docks page, this behaviour is slightly jarring and not what I think users would expect.

### Steps To Reproduce

Create a popup which uses `hover-click` and hover over it, then hover away.

### Anything else?

I think this could be fixed by just adding `node.addEventListener('mouseout', close, true);`
to https://github.com/skeletonlabs/skeleton/blob/master/src/lib/utilities/Popup/popup.ts#L233

**Comment by endigo9740** [comment] 2023-04-13 03:49
@DevOfManyThings Just to ensure we're clear, `hover-click` is a semantic name that describes the expected behavior on open + close. So in this case the expectation is on hover the popup will appear, then on click outside the popup will be removed.

Hover in this case is `mouseover` and `mouseout` events of course. The `hover-hover` event is just referred to as `hover` for simplicity. So adding `mouseout` for the `hover-click` would not be the desired functionality here.

Does that make sense?

**Comment by DevOfManyThings** [comment] 2023-04-13 15:39
@endigo9740 Ah my apologies, when I looked at it I thought it was effectively "the best of both worlds", as `hover` is nice on desktop, but isn't great for mobile. I assumed if you hovered over it to open, and if you hovered away that would close, if you `click` to open then you need to `click` to close. Basically a way to support both desktop + mobile without needing to create two popup instances. But what you've said makes sense now that it's been explained.

I imagine one of the most common use cases for popup is as a tooltip, where it the user hovers over an icon/button the tooltip displays additional info, if they click that button/icon the popup disappearing makes sense, but if they don't then the popup is just left hovering there for something they're not going to interact with so they need to click to clear the space, which isn't smooth in my opinion.

If this is the desired behaviour then you can close the ticket, I'll personally probably only stick with `click` then as that feels consistent to me, which is a shame because `hover` is nice on desktop, but doubling the amount of popups on a screen (one for desktop `hover`, one for mobile `click`, using tailwind to hide the one not relevant based on screen size) isn't great for performance reasons (I tried it and it started to cause issues).

**Comment by endigo9740** [comment] 2023-04-13 17:14
Ahh that's a totally reasonable assumption, and may highlight room for improvement in our docs.

Personally `click` and `hover` are the only events I'd use. The former for an interactive popup, like a dropdown, and the later for tooltips. The thing about hover events in general is they are not supported on mobile or touch devices, so they have to be used sparingly. Never for critical information. Again, this is an area where we might should include this recommendation in a more prominent fashion in our docs!

I would also recommend you check out the use case of the `focus` and `focus-click` events. They're great for input-based popups, such as a autocomplete popup!

Since it sounds like we're on the same page here and no further action is required I'm going to go ahead and close this out.

**Closed by endigo9740** 2023-04-13 17:14 UTC
Labels: bug

**Comment by DevOfManyThings** [comment] 2023-04-13 17:29
@endigo9740 Would you be open to a feature request for another event type that works as I'd described? I think something which offers both hover + click functionality would be quite useful to get the benefits of hover on desktop, whilst still supporting click for touch/mobile.
I think the main scenario this covers is tooltips as desktop users are quite used to those working on `hover`, but they still need to work for touch/mobile as well.

**Comment by endigo9740** [comment] 2023-04-13 17:51
@DevOfManyThings I'd say only if you're open to sending a PR to implement as well. We've had a huge uptick in feature requests lately and I'm currently the only full time contributor to Skeleton. But I'm splitting my time between Skeleton and Skeleton Labs projects. So long story short, it would probably sit idle for a quite a while, given it's priority would be low.

**Comment by DevOfManyThings** [comment] 2023-04-13 18:27
Yeah I was actually thinking it could be a good first PR as I _think_ it might be simple enough, I'll raise the feature request and leave it for a bit to see if anyone has feedback, and take a crack at it. If something comes up and I don't get the time then completely understand its a low priority!
