### ISSUE TITLE
The event of Amout change not giving updated values of the selected option

### ISSUE THREAD

**Issue by Hamxa003** [skeletonlabs/skeleton#2180] opened 2023-10-24 11:37 UTC
### More Information

`<script lang="ts">`
import {
		tableSourceMapper,
		Paginator,
		type PaginationSettings
	} from '@skeletonlabs/skeleton';

let listMember: ClassMember[];
	let selectedClass = Object.keys(data.item)?.[0] ?? '';
	let paginationSettings: PaginationSettings;
	let offset: number = 0;
	let limit: number = 5;

	$: listMember = data.item?.[selectedClass] || [];
	$: paginationSettings = {
		offset,
		limit,
		size: listMember.length,
		amounts: [5, 10, 15, 20]
	};

function onPageChange(e: CustomEvent): void {
		offset = e.detail;
	}

	function onAmountChange(e: CustomEvent): void {
		limit = e.detail;
	}

`</script>`

	<Paginator
				bind:settings={paginationSettings}
				justify="justify-between"
				on:page={onPageChange}
				on:amount={onAmountChange}
			/>

**Comment by Sarenor** [comment] 2023-10-24 11:41
Do I parse this correctly, the event received by ``onAmountChange`` is not correct?

**Comment by Hamxa003** [comment] 2023-10-24 11:44
yes, it always return same amount that I give it initially i.e. 5 or 10

**Comment by Sarenor** [comment] 2023-10-24 12:02
If you check the console on the  [paginators page](https://www.skeleton.dev/components/paginators) you'll see that it's working there.

It is therefore probably not a bug, so I'll be closing this.

So sad as I am to say it, this issue is either in the version of Skeleton you're using which you haven't shared or in the code which you did share.
It is a bit of a mess though and I don't really feel like debugging it like that.
You're welcome to check the ``Page Source`` button of the paginators page to see how it's done there or to format the code here to ease debugging.

If you want to, you can also try to recreate a reproduction in [Stackblitz](https://stackblitz.com/fork/github/skeletonlabs/repl/tree/main/welcome), that's probably the quickest way to get help.
We also offer a support channel in the Skeleton Discord.

**Closed by Sarenor** 2023-10-24 12:02 UTC
Labels: bug

**Comment by endigo9740** [comment] 2023-10-24 15:09
Also Hamxa, I apologize, the code was not formatted properly so I attempted to update that to improve readability. But either myself or GitHub appears to have snipped off a portion of the code at the bottom with the component itself. If you wish, please feel free to restore this.

Per Dom's message above - we typically request folks post enough to allow us to replicate the issue presented. It doesn't sound like that was the case here. If you can provide more information, we're happy to help debug here.

If you need to check what version of Skeleton you're running, try `npm list` in your terminal.

Thanks!
