### ISSUE TITLE
White flicker when clicking on form fields

### ISSUE THREAD

**Issue by jerebtw** [skeletonlabs/skeleton#760] opened 2023-01-03 18:27 UTC
### Current Behavior

Currently it flickers white when you click on an form field for example a input (see the videos below)

https://user-images.githubusercontent.com/49494752/210417672-588304de-579d-4869-b875-418026400222.mp4

https://user-images.githubusercontent.com/49494752/210417887-ba7cb60a-d92e-46bb-a6cc-ef093c8ffd65.mp4

### Steps To Reproduce

Go to the form page in the documents (https://www.skeleton.dev/elements/forms/preview)

### Anything else?

- The issue occurs in the latest versions of Chrome, Firefox

**Comment by endigo9740** [comment] 2023-01-03 19:13
Just noting this doesn't occur on the Tailwind plugin preview page, so it's not an inherited issue from that.
https://tailwindcss-forms.vercel.app/

**Comment by endigo9740** [comment] 2023-01-03 19:44
@jerebtw I've pushed a small fix for this to our dev branch, if you wish to preview:
https://dev.skeleton.dev/elements/forms/preview

The issue was related to use the use of Tailwind's `transition-all` class. When I replaced that with `transition` the issue stoped. I'm not 100% of the cause, but the fix works so I won't complain!

Furthermore, I realized we were double up on both ring and border style for inputs, making the input edges look much thicker than intended. So I've resolved that while I was at it. You may note that each theme has slightly thinner borders, but these should now match the theme settings and user expectations.

Given this is merged into our dev branch, it means it'll be a part of the next release, scheduled for a week from today. Thanks for reporting this!

**Closed by endigo9740** 2023-01-03 19:44 UTC
Labels: bug

**Comment by jerebtw** [comment] 2023-01-03 19:50
It looks really great thanks 😄
