### ISSUE TITLE
Modal's boolean field 'open' stops changing value when onOpenChange handler is implemented

### ISSUE THREAD

**Issue by Shavinder** [skeletonlabs/skeleton#2965] opened 2024-11-14 17:45 UTC
### Current Behavior

If an onOpenChange handler is implemented when using a modal, the openState variable bound to the boolean field 'open' stops reflecting the modal's current open/close state. 

### Expected Behavior

`openState` should be true when the modal is open and false when it is not.

### Steps To Reproduce

```
<script>
	import { Modal } from '@skeletonlabs/skeleton-svelte';

	let openState = $state(false);

	function modalClose() {
        console.log(`openState: ${openState}`);
		openState = false;
	}
    function openChangeHandler(details) {
        console.log(details.open);
    }
</script>   

<Modal
	bind:open={openState}
    onOpenChange={openChangeHandler}
	triggerBase="btn preset-tonal"
	contentBase="card bg-surface-100-900 p-4 space-y-4 shadow-xl max-w-screen-sm"
	backdropClasses="backdrop-blur-sm"
>
	{#snippet trigger()}Open Modal{/snippet}
	{#snippet content()}
		<header class="flex justify-between">
			<h2 class="h2">Modal Example</h2>
		</header>
		<article>
            <p class="text-primary-500">openState is {openState}</p>
			<p class="opacity-60">Lorem ipsum dolor </p>
		</article>
		<footer class="flex justify-end gap-4">
			<button type="button" class="btn preset-tonal" onclick={modalClose}>Cancel</button>
			<button type="button" class="btn preset-filled" onclick={modalClose}>Confirm</button>
		</footer>
	{/snippet}
</Modal>

```
Now `openState` remains false permanently as seen by its value shown in the modal content as well as the logged statement in the `modalClose()` function.

**Comment by Hugos68** [comment] 2024-11-16 20:53
I'm pretty sure this is a duplicate of what is happening in #2967. When passing a handler like `onOpenChange`, the internal one is overriden so the `open` or `checked` or whatever bindable state we expose is not being syncronized anymore. This can be fixed in the same way as how the `Switch` can be fixed, I've left [this comment](https://github.com/skeletonlabs/skeleton/pull/2967#discussion_r1845235163) describing and fixing the issue.

**Comment by Hugos68** [comment] 2024-11-17 15:57
@endigo9740 This can be closed.

**Closed** 2024-12-09 20:47 UTC
Labels: bug
