### ISSUE TITLE
This happens after I install the skeleton UI project

### ISSUE THREAD

**Issue by gabrielatwell1987** [skeletonlabs/skeleton#1732] opened 2023-07-06 21:18 UTC
### Current Behavior

This happens after I install skeletonUI and I do 'npm run dev': I get an error that says

[plugin:vite:css] [postcss] postcss-import: C:\Users\Gatwe\Desktop\Sveltekit\e-commerce\node_modules\@skeletonlabs\skeleton\dist\styles\partials\core.css:3:1: `@layer base` is used but no matching `@tailwind base` directive is present.
C:/Users/Gatwe/Desktop/Sveltekit/e-commerce/node_modules/@skeletonlabs/skeleton/dist/styles/partials/core.css:3:1
1  |  /* Stylesheet: skeleton.css */
2  |  
3  |  /*
   |   ^
4  |  - Slated to replace `all.css` in the next major release
5  |  - All available stylesheets are imported
CssSyntaxError: [postcss] postcss-import: C:\Users\Gatwe\Desktop\Sveltekit\e-commerce\node_modules\@skeletonlabs\skeleton\dist\styles\partials\core.css:3:1: `@layer base` is used but no matching `@tailwind base` directive is present.
    at Input.error (C:\Users\Gatwe\Desktop\Sveltekit\e-commerce\node_modules\postcss\lib\input.js:106:16)
    at AtRule.error (C:\Users\Gatwe\Desktop\Sveltekit\e-commerce\node_modules\postcss\lib\node.js:115:32)
    at normalizeTailwindDirectives (C:\Users\Gatwe\Desktop\Sveltekit\e-commerce\node_modules\tailwindcss\lib\lib\normalizeTailwindDirectives.js:72:32)
    at C:\Users\Gatwe\Desktop\Sveltekit\e-commerce\node_modules\tailwindcss\lib\processTailwindFeatures.js:30:98
    at plugins (C:\Users\Gatwe\Desktop\Sveltekit\e-commerce\node_modules\tailwindcss\lib\plugin.js:38:63)
    at LazyResult.runOnRoot (C:\Users\Gatwe\Desktop\Sveltekit\e-commerce\node_modules\postcss\lib\lazy-result.js:357:16)
    at LazyResult.runAsync (C:\Users\Gatwe\Desktop\Sveltekit\e-commerce\node_modules\postcss\lib\lazy-result.js:286:26)
    at LazyResult.async (C:\Users\Gatwe\Desktop\Sveltekit\e-commerce\node_modules\postcss\lib\lazy-result.js:160:30)
    at LazyResult.then (C:\Users\Gatwe\Desktop\Sveltekit\e-commerce\node_modules\postcss\lib\lazy-result.js:436:17
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

### Expected Behavior

To install a clean project. Every day so far, it has installed a clean project that works. Today is the first day that it has errored out.

### Steps To Reproduce

run 'npm create skeleton-app@latest <file_name>'

once it installs I run 'npm run dev'

And when the page loads I get a Svelte error (the error I posted above)

### More Information

I really hope you guys fix this because skeletonUI is really easy to create sveltekit projects with tailwind css. Please email me at gabriel.atwell@proton.me if you need more info.

**Comment by endigo9740** [comment] 2023-07-06 21:29
Duplicate of: https://github.com/skeletonlabs/skeleton/issues/1731

**Closed by endigo9740** 2023-07-06 21:29 UTC
Labels: bug
