### ISSUE TITLE
Source code button for typography redirects to a 404

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#1597] opened 2023-05-30 00:22 UTC
### Link to the Page

https://www.skeleton.dev/elements/typography

### Describe the Issue (screenshots encouraged!)

![image](https://github.com/skeletonlabs/skeleton/assets/63101006/6e1a7acc-845e-48b2-a86b-d0ad05129ce4)
The button redirects to the wrong page (probably due to the recent monorepo migration)

Currently creating a PR for this.

**Comment by endigo9740** [comment] 2023-05-30 02:38
@SebasF1349 was working on a PR for a few odds and ends like this, I don't care who handles it, but let's try to avoid doubling up on the effort.

**Comment by SebasF1349** [comment] 2023-05-30 10:49
My bad, I was working on it before this issue but should have created an issue myself. Sorry.

**Comment by endigo9740** [comment] 2023-05-31 17:19
Duplicate of: https://github.com/skeletonlabs/skeleton/pull/1599

**Closed** 2023-05-31 17:19 UTC
Labels: documentation, duplicate
