### ISSUE TITLE
Bug in Popups in docs

### ISSUE THREAD

**Issue by saturnonearth** [skeletonlabs/skeleton#1095] opened 2023-03-05 19:40 UTC
### Current Behavior

When you click all three popup examples, and then try to scroll, it jumps repeatably to the top of the page.

![chrome_cNBrB8Uej5](https://user-images.githubusercontent.com/12503538/222981925-4f1fc178-ef83-4a29-8540-4d6a13241770.gif)

### Steps To Reproduce

1. Go to https://www.skeleton.dev/utilities/popups
2. Click all three pop-up examples.
3. Attempt to continuously scroll downwards.

### Anything else?

Tested on Windows 11 Chrome Version 110.0.5481.178

**Comment by endigo9740** [comment] 2023-03-05 23:46
Duplicate of: https://github.com/skeletonlabs/skeleton/issues/1018

**Closed by endigo9740** 2023-03-05 23:47 UTC
Labels: bug
