### ISSUE TITLE
Oncontextmenu

### ISSUE THREAD

**Issue by cycle4passion** [skeletonlabs/skeleton#1094] opened 2023-03-05 19:16 UTC
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Please forward oncontextmenu events for all components. This should allow it to be used for more complex right-click options like popups creating custom context menus.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment] 2023-03-05 23:46
Duplicate of: https://github.com/skeletonlabs/skeleton/issues/819

**Closed by endigo9740** 2023-03-05 23:46 UTC
Labels: feature request
