### ISSUE TITLE
Tabs Tabindex Accessibility

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#1434] opened 2023-05-04 23:35 UTC
### Current Behavior

Devtools like Axe mark tabs as a critical accesibility error since the tabindex=0 and that isn't friendly to assitive technologies according to: https://www.a11yproject.com/posts/how-to-use-the-tabindex-attribute/

### Reproduction / Steps To Reproduce

Use Tabs and run some accessability tools

**Comment by ryceg** [comment] 2023-05-04 23:38
I'll take this issue @endigo9740

**Comment by endigo9740** [comment] 2023-05-05 00:32
Dang it @Hugos68 I told you not to look at our docs :P

Thanks @ryceg

**Comment by endigo9740** [comment] 2023-05-05 00:49
Also @Hugos68 this is a duplicate of: https://github.com/skeletonlabs/skeleton/pull/1398

I'll aim to merge this tomorrow, so it'll be part of the next release.

**Closed by endigo9740** 2023-05-05 00:49 UTC
Labels: bug
