### ISSUE TITLE
Avatars Issue - Non Square Aspect Ratio & Handling Rectangle Images (+Safari Behaving Differently)

### ISSUE THREAD

**Issue by fatstack** [skeletonlabs/skeleton#2446] opened 2024-01-28 17:53 UTC
### Current Behavior

Avatars are behaving strange for me on 1.7.1 (presumably 1.7.0 also, seeing that had changes for Avatars). If I downgrade to 1.6.1 I do not experience these issues.

So a few cases:
- Using a rectangle image in an avatar. For landscape images, there can be cases where the the image won't be zoomed in enough and the top of the avatar will be empty space. The same images didn't have this issue in 1.6.1. You can see this in the first example in the images.
- Portrait orientation rectangle image + using the class 'absolute' on the avatar component will cause the avatar to grow vertically in Safari (last example in the image) - but not in Firefox and Chrome.
- The other examples I just noticed as I was making examples to report. It seems like having the avatars inside a flex div affects them.

Safari:
<img width="343" alt="safari" src="https://github.com/skeletonlabs/skeleton/assets/40495144/a9688f85-0f7e-4315-ac47-4e53f24dc2a6">

Firefox (Chrome is the same):
<img width="354" alt="firefox + chrome" src="https://github.com/skeletonlabs/skeleton/assets/40495144/a0bcbaf7-1dbf-4467-87d3-1e18ad948125">

### Expected Behavior

Avatar should always have a square aspect ratio and the image should fill the whole avatar.

### Steps To Reproduce

```
<div class="flex h-96">
  <div>
	  <Avatar
		  src="https://i.ytimg.com/vi/cB4dYfFgaME/maxresdefault.jpg"
		  background="bg-red-500"
	  />
  </div>
  <Avatar
	  src="https://i.ytimg.com/vi/cB4dYfFgaME/maxresdefault.jpg"
	  background="bg-red-500"
  />
  <div>
	  <Avatar
		  src="http://theloziers.com/mediac/400_0/media/long_cat1.gif"
		  background="bg-red-500"
	  />
  </div>
  <Avatar
	  src="http://theloziers.com/mediac/400_0/media/long_cat1.gif"
	  background="bg-red-500"
  />
  <div class="relative bg-blue-500">
	  <Avatar
		  src="http://theloziers.com/mediac/400_0/media/long_cat1.gif"
		  background="bg-red-500"
		  class="absolute"
	  />
  </div>
</div>
```

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/skeletonlabs-repl-1j8gm1?file=src%2Froutes%2F%2Bpage.svelte

### More Information

Thanks for the great work :)

**Comment by endigo9740** [comment] 2024-01-28 18:46
@fatstack so first off I appreciate the use of the long cat meme here. That's perfect.

I've gone ahead and created a proper minimal reproduction to help illustrate the issue here. Note the green background to help emphasize the issue here:

![Screenshot 2024-01-28 at 12 40 28 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/78ccc9ca-60a3-499a-8e14-000f8aeded35)

So this is due to the interaction between the avatar and surrounding flexbox. By default if you use `flex` but don't specify an `item-` class the items within will try to fill the available space if a height is not defined on each item. In the case of avatars we use:

```
w-[whatever] aspect-square
```

Which will try to force the element to have equal height/width. However the flexbox styles take precedence here. So have a few options:

1. Define an an [Align Items](https://tailwindcss.com/docs/align-items) value on the flexbox, such as `items-center` or `.items-start`
2. Remove the height setting on the surrounding flex element
3. Set a height on the surrounding flex element that matches the desired avatar height
4. Define the Avatar height, which doesn't have a set prop, but instead can be done via `class="h-[x]`

Note that this issue will be resolved in Skeleton v3, as we will have access to the new [size property](https://tailwindcss.com/docs/size) in Tailwind that sets both height/width evenly! For now, I'll close this issue and link this to the appropriate v3 thread for visibility as we implement the new iteration soon.

Thanks!

**Closed by endigo9740** 2024-01-28 18:46 UTC
Labels: bug
