### ISSUE TITLE
Popup does not work in CSR mode when popup is bound to an element passed in as slot content

### ISSUE THREAD

**Issue by fnimick** [skeletonlabs/skeleton#1017] opened 2023-02-22 22:09 UTC
### Current Behavior

When rendering in CSR mode (`export const ssr = false`), with a `use:popup` attached to an element which is passed in as slot content, rendering fails with a client-side javascript error.

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'ownerDocument')
    at getWindow (floating-ui.dom.browser.mjs:6:39)
    at isNode (floating-ui.dom.browser.mjs:59:27)
    at getNodeName (floating-ui.dom.browser.mjs:36:10)
    at getParentNode (floating-ui.dom.browser.mjs:297:7)
    at getNearestOverflowAncestor (floating-ui.dom.browser.mjs:313:22)
    at getOverflowAncestors (floating-ui.dom.browser.mjs:330:30)
    at autoUpdate (floating-ui.dom.browser.mjs:593:202)
    at popup (popup.js:188:5)
    at Object.mount [as m] (http://localhost:5173/src/routes/(:5173/test)/+page.svelte:87:53)
    at mount (Foo.svelte:32:18)
```

### Steps To Reproduce

Attach popup to an element, then pass that element into a parent component. It doesn't matter what the parent component does, my reproduction has a blank component which contains only `<slot />`.

### Anything else?

Reproduction repository: https://github.com/fnimick/skeleton-popup-bug-repro

Removing the dummy `Foo` wrapper around the Menu button, or setting ssr back to true, resolves the issue.

**Comment by endigo9740** [comment] 2023-03-07 20:39
@fnimick I wanted to let you know I've been able do the following:

- Replicate your issue as described in your repro in the default configuration
- Confirm that this works as intended if SSR is set `true` in `layout.server.ts`
- Confirm that the popup works as intended if the popup trigger is not within a component slot
- Confirm that any Svelte action works as intended if implemented on an element within a component slot

However, I may have as proposed solution for you, which is to move the popup itself into the slot container as well. Leaving everything default and moving your pop, I now see this functionally working with no error.

![Screenshot 2023-03-07 at 2 34 56 PM](https://user-images.githubusercontent.com/1509726/223546164-29a3e1ea-e6d2-43a9-ba76-2b290a5fd4c9.png)

![Screenshot 2023-03-07 at 2 35 51 PM](https://user-images.githubusercontent.com/1509726/223546343-d933b736-36be-4242-bb69-7a05c9d4146e.png)

Unfortunately I'm not sure there's a viable solution with the popup decoupled from the trigger. My guess is something about the way Svelte renders component slot content makes it so external elements are out of scope. In fact, you can test this by deleting the popup altogether, when doing so you'll note you get the exact same error!

![Screenshot 2023-03-07 at 2 37 21 PM](https://user-images.githubusercontent.com/1509726/223546724-0dd02abc-77b5-49b2-991d-e268b25bd4e8.png)

![Screenshot 2023-03-07 at 2 37 29 PM](https://user-images.githubusercontent.com/1509726/223546727-bda2e58f-216e-4b7d-8fad-e6f06f8b3d78.png)

So really, the main issue on our end would be better error handling when the paired popup element cannot be found. This is a known issue, but I've noted it as something to address alongside some other extensions to the popup utility feature here:
https://github.com/skeletonlabs/skeleton/issues/1014#issuecomment-1458841380

Unfortunately I don't know that we can do anything else for you here, so I'm gonna mark this closed. Hope this helps though!

**Closed by endigo9740** 2023-03-07 20:39 UTC
Labels: bug
