### ISSUE TITLE
Lightswitch Initial State always dark

### ISSUE THREAD

**Issue by DGne-Nurag** [skeletonlabs/skeleton#1341] opened 2023-04-18 11:09 UTC
### Current Behavior

Regardless of current active mode (light or dark) the button always is dark state on first page load.

### Reproduction / Steps To Reproduce

- Open Browser in incognito mode
- Set Browser to light mode
- Open skeleton.dev
- toggle Theme Menu

Theme is in light mode but the Lightswitch toggle switch is on Dark mode with the moon icon

**Comment by endigo9740** [comment] 2023-04-18 15:15
There's not enough information to go on here. We'll need to know the full context of how this is being used:

- Was this project setup manually or via the CLI?
- If you set this up manually did you implement `darkMode: 'class'` into your Tailwind config?
- If you set this up manually did you add `class="dark"` on the HTML element in your app.html file?
- Where the Lightswitch component in the scope of your page?
- Is this occurring locally or only when deployed?
- If it's occurring when deployed, what adapter are you using?
- What SSR strategy are you using? As this can affect the way the lightswitch operates.

One thing of note is the Lightswitch needs to be rendered on load for every page or it will not work at all. If it's hidden within a dynamically added portion of the UI this will not suffice.

**Comment by Sarenor** [comment] 2023-04-18 16:40
I think he's talking about Skeleton.dev, so you're the best instance to answer all those questions ;)

It should just be an inconsistency between detected theme and displayed lightswitch state, I haven't had the chance to check yet though.

**Comment by DGne-Nurag** [comment] 2023-04-19 09:03
> I think he's talking about Skeleton.dev, so you're the best instance to answer all those questions ;)

That's right. It is independent of installation type and present in the actual website of the project.

**Comment by endigo9740** [comment] 2023-04-19 15:28
@DGne-Nurag Ok, but we need steps to replicate. At least know what browser/OS. As I have been unable to replicate this on multiple browsers for Mac and Windows. But this is the first report we've seen of this so it makes me feel it's isolated to you.

I might suggest purging cookies and other local storage values within your browser for the site to see if that helps. Likewise see if the issue persists in an Incognito window or another browser. If the issues does not persist when doing this you likely have an extension causing the issue.

**Comment by zivillian** [comment] 2023-04-19 15:51
@endigo9740 I can reproduce this issue in chrome, firefox and edge on windows. Simply opening https://www.skeleton.dev/ shows the light theme but a switch suggesting I was using the dark theme:
![grafik](https://user-images.githubusercontent.com/6039253/233130812-7bde11ce-1e99-4c40-afd0-1f478dbac37b.png)

Since I'm normally not using edge this cannot be caused by local storage or cookies.

**Comment by endigo9740** [comment] 2023-04-19 22:57
Testing on Windows in Edge (which I don't use regularly)

The initial state on load:
![image](https://user-images.githubusercontent.com/1509726/233217091-e46070ec-1e9a-4116-ac56-27590e815b30.png)

Toggling light mode:
![image](https://user-images.githubusercontent.com/1509726/233217190-150aac9f-d161-475e-b26b-73010005b168.png)

Refreshing in either state persists the selected value.

So currently I'm still unable to replicate. If we can't replicate we can't troubleshoot, and if we can't troubleshoot we can't resolve  any sort of issue.

**Comment by Sarenor** [comment] 2023-04-20 05:59
I could recreate it.
It's specifically when your system/browser is set to light mode, so that it loads with light-theme initially:
<img width="609" alt="image" src="https://user-images.githubusercontent.com/31982384/233271360-ae3ba943-83cd-4247-ae95-9a9fbe780a00.png">
Sorry, work has been kind of unkind the last couple of days, otherwise I'd have tested earlier.

It's probably a small inconsistency with the mode detection not updating the displayed value correctly.

**Comment by DGne-Nurag** [comment] 2023-04-20 07:51
- Firefox incognito mode
- open developer tools
- switch to inspector and click the little sun
![image](https://user-images.githubusercontent.com/661697/233297511-65d0a18b-4380-4d7b-ad15-39d126b344cb.png)

- open skeleton.dev
- the side is in light mode but the switch is in moon position
![image](https://user-images.githubusercontent.com/661697/233297617-4fffb1e7-20b2-4ae7-b959-dca4e0278cc2.png)

**Comment by robotpapier** [comment] 2023-04-29 06:36
Hi,
I use this workaround to check if variables in localstorage responsible for the lightswitch's state exist or not.
If not I check the browser color scheme prefered and init the localstorage variable accordingly.
Hope it helps!

`import { browser } from '$app/environment';
	if (browser) {
		// === SYNC Lightswitch state with current browser and site color scheme
		if (!window.localStorage.getItem('modeCurrent')) {
			// Check color schemes prefered of the browser
			if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
				// dark mode
				console.log('currently dark mode!');
				window.localStorage.setItem('modeCurrent', 'false');
				window.localStorage.setItem('modeUserPrefers', 'false');
			} else {
				// light mode
				console.log('currently light mode!');
				window.localStorage.setItem('modeCurrent', 'true');
				window.localStorage.setItem('modeUserPrefers', 'true');
			}
		}

		// Check color schemes changes
		window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', ({ matches }) => {
			if (matches) {
				console.log('change to dark mode!');
				//window.localStorage.setItem('modeCurrent', 'false');
				//window.localStorage.setItem('modeUserPrefers', 'false');
			} else {
				console.log('change to light mode!');
				//window.localStorage.setItem('modeCurrent', 'true');
				//window.localStorage.setItem('modeUserPrefers', 'true');
			}
		});
	}`

**Comment by Mahmoud-zino** [comment] 2023-04-29 20:57
I faced the same issue and another workaround was by calling the `setInitialClassState()` in `onMount` after setting the `$modeCurrent` to sync the lightswitch.

From the function name I know it was not intended to be called again, so I don't think it was the best solution... I will be happy to change it when this gets fixed

**Comment by Mahmoud-zino** [comment] 2023-05-05 14:58
btw Can I work on this issue?

**Comment by endigo9740** [comment] 2023-05-05 16:04
@Mahmoud-zino sure go for it. I'll assign it to you now. Thanks!

**Closed** 2023-05-05 18:37 UTC
Labels: bug
